# This is an example workflow you could use to
# upload to PyPI (using a different action) and conda-forge (using this action).
# In this example we use "mylib" as the name of the example project (on both PyPI and CF)
# This assumes a source-only upload to PyPI.
name: PyPI Upload and Conda-Forge PR

on:
  release:
    types: [published]

jobs:
  Upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2

    - name: Build wheel and source tarball
      id: build_tarball
      run: |
        python setup.py sdist
        # Find the version number. There are better ways of doing this
        version=$(head -1  mylib/version.py | cut  -d "'" -f 2)
        sha=$(shasum -a 256 dist/mylib-${version}.tar.gz | awk '{print $1}')
        # These lines tell the workflow to save these parameters for future
        # workflow steps. We use them below.
        echo "::set-output name=tarball-sha::${sha}"
        echo "::set-output name=pypi-version::${version}"

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        # For testing you can uncomment this option, which will
        # push to the test version of PYPI
        #repository_url: https://test.pypi.org/legacy/

    - name: Make PR on conda forge feedstock
      uses: joezuntz/conda-forge-feedstock-pr-action@v1.0
      with:
        # this is usually the same as your project name, but not quite always
        feedstock_name: mylib
        # the token you created 
        token: ${{ secrets.FEEDSTOCK_TOKEN }}
        # The version number of the new pypi entry. It was
        # saved in the "Build wheel and source tarball" phase
        # above, and this is how you access it
        version: ${{ steps.build_tarball.outputs.pypi-version }}
        # Similarly ,the SHA256 hash of the tarball
        hash: ${{ steps.build_tarball.outputs.tarball-sha }}
        # The github user name where the conda-forge fork lives
        fork_owner: your_user_name
        # Email address is used to list you as the author of the commit
        email_address: your_user_name@your_org.org
        # The name of the branch to target on the conda-forge
        # feedstock.  This is normally "main" but used to be "master"
        # so I don't know if there are some still called that.
        # You can leave this out and it will default to "main"
        # branch_name: main
